
int assistir(int duracao ,int valor){
	int pagamento;
	int n = 1;
	int i;
do{
	system("cls");
			printf("\n\n\t\t                 Pagamento                     ");
			printf("\n\t\t+-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-+");
			printf("\n\t\t|                  Nota Fiscal                  |");
			printf("\n\t\t|                                               |");
			printf("\n\t\t|                                               |");
			printf("\n\t\t|                                               |");
			printf("\n\t\t|                                               |");
			printf("\n\t\t|                                               |");
			printf("\n\t\t|                                               |");
			printf("\n\t\t|   Pix: 123.456.789.10                         |");
			printf("\n\t\t|   Ingresso: 20.00                             |");
			printf("\n\t\t|   Combo 1: %d                                  |",comida.combo1);
			printf("\n\t\t|   Combo 2: %d                                  |",comida.combo2);
			printf("\n\t\t|   Pipoca: %d                                   |",comida.pipoca);
			printf("\n\t\t|   Coca: %d                                     |",comida.coca);
			printf("\n\t\t|                                               |");
			printf("\n\t\t|                                               |");
			printf("\n\t\t|   Valor Total c/Desconto: %d.00               |", valor);
			printf("\n\t\t|                                               |");
			printf("\n\t\t|                                               |");
			printf("\n\t\t|                                               |");
			printf("\n\t\t|                                               |");
			printf("\n\t\t|                +-----------+                  |");
			printf("\n\t\t|                | 1 - Pagar |                  |");
			printf("\n\t\t|                +-----------+                  |");
			printf("\n\t\t+-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-+\n\n\t\t");
			scanf("%d", &pagamento);
			if(pagamento != 1){
				printf("\n\n\t\tTem que pagar caloteiro..");
				Sleep(2000);
			}
}while(pagamento != 1);
	system("cls");
	printf("\n\n\t\t  *•.¸¸¸.•*¨¨*•.¸¸¸.•*•  ¸.•*¨¨*•.¸¸¸.•*•  •*\n"); 
	printf("\t\t   ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ B¦¦  \n");
	printf("\t\t*•  *•.¸¸¸.•*¨¨*•.¸¸¸.•*• ¸.•*¨¨*•.¸¸¸.•*•  •«\n");
	Sleep(50);
	system("cls");
	printf("\n\n\t\t  *•.¸¸¸.•*¨¨*•.¸¸¸.•*•  ¸.•*¨¨*•.¸¸¸.•*•  •*\n"); 
	printf("\t\t   ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦B¦O¦¦  \n");
	printf("\t\t*•  *•.¸¸¸.•*¨¨*•.¸¸¸.•*• ¸.•*¨¨*•.¸¸¸.•*•  •«\n");
	Sleep(50);
	system("cls");
	printf("\n\n\t\t  *•.¸¸¸.•*¨¨*•.¸¸¸.•*•  ¸.•*¨¨*•.¸¸¸.•*•  •*\n"); 
	printf("\t\t   ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦B¦O¦M¦¦  \n");
	printf("\t\t*•  *•.¸¸¸.•*¨¨*•.¸¸¸.•*• ¸.•*¨¨*•.¸¸¸.•*•  •«\n");
	Sleep(50);
	system("cls");
	printf("\n\n\t\t  *•.¸¸¸.•*¨¨*•.¸¸¸.•*•  ¸.•*¨¨*•.¸¸¸.•*•  •*\n"); 
	printf("\t\t   ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦B¦O¦M¦ ¦¦  \n");
	printf("\t\t*•  *•.¸¸¸.•*¨¨*•.¸¸¸.•*• ¸.•*¨¨*•.¸¸¸.•*•  •«\n");
	Sleep(50);
	system("cls");
	printf("\n\n\t\t  *•.¸¸¸.•*¨¨*•.¸¸¸.•*•  ¸.•*¨¨*•.¸¸¸.•*•  •*\n"); 
	printf("\t\t   ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦B¦O¦M¦ ¦F¦¦  \n");
	printf("\t\t*•  *•.¸¸¸.•*¨¨*•.¸¸¸.•*• ¸.•*¨¨*•.¸¸¸.•*•  •«\n");
	Sleep(50);
	system("cls");
	printf("\n\n\t\t  *•.¸¸¸.•*¨¨*•.¸¸¸.•*•  ¸.•*¨¨*•.¸¸¸.•*•  •*\n"); 
	printf("\t\t   ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦B¦O¦M¦ ¦F¦I¦¦  \n");
	printf("\t\t*•  *•.¸¸¸.•*¨¨*•.¸¸¸.•*• ¸.•*¨¨*•.¸¸¸.•*•  •«\n");
	Sleep(50);
	system("cls");
	printf("\n\n\t\t  *•.¸¸¸.•*¨¨*•.¸¸¸.•*•  ¸.•*¨¨*•.¸¸¸.•*•  •*\n"); 
	printf("\t\t   ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦B¦O¦M¦ ¦F¦I¦L¦¦  \n");
	printf("\t\t*•  *•.¸¸¸.•*¨¨*•.¸¸¸.•*• ¸.•*¨¨*•.¸¸¸.•*•  •«\n");
	Sleep(50);
	system("cls");
	printf("\n\n\t\t  *•.¸¸¸.•*¨¨*•.¸¸¸.•*•  ¸.•*¨¨*•.¸¸¸.•*•  •*\n"); 
	printf("\t\t   ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦B¦O¦M¦ ¦F¦I¦L¦M¦¦  \n");
	printf("\t\t*•  *•.¸¸¸.•*¨¨*•.¸¸¸.•*• ¸.•*¨¨*•.¸¸¸.•*•  •«\n");
	Sleep(50);
	system("cls");
	printf("\n\n\t\t  *•.¸¸¸.•*¨¨*•.¸¸¸.•*•  ¸.•*¨¨*•.¸¸¸.•*•  •*\n"); 
	printf("\t\t   ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦B¦O¦M¦ ¦F¦I¦L¦M¦E¦¦  \n");
	printf("\t\t*•  *•.¸¸¸.•*¨¨*•.¸¸¸.•*• ¸.•*¨¨*•.¸¸¸.•*•  •«\n");
	Sleep(50);
	system("cls");
	printf("\n\n\t\t  *•.¸¸¸.•*¨¨*•.¸¸¸.•*•  ¸.•*¨¨*•.¸¸¸.•*•  •*\n"); 
	printf("\t\t   ¦ ¦ ¦ ¦ ¦ ¦ ¦B¦O¦M¦¦F¦I¦L¦M¦E¦ ¦¦  \n");
	printf("\t\t*•  *•.¸¸¸.•*¨¨*•.¸¸¸.•*• ¸.•*¨¨*•.¸¸¸.•*•  •«\n");
	Sleep(50);
	system("cls");
	printf("\n\n\t\t  *•.¸¸¸.•*¨¨*•.¸¸¸.•*•  ¸.•*¨¨*•.¸¸¸.•*•  •*\n"); 
	printf("\t\t   ¦ ¦ ¦ ¦ ¦ ¦B¦O¦M¦ ¦F¦I¦L¦M¦E¦ ¦A¦¦  \n");
	printf("\t\t*•  *•.¸¸¸.•*¨¨*•.¸¸¸.•*• ¸.•*¨¨*•.¸¸¸.•*•  •«\n");
	Sleep(50);
	system("cls");
	printf("\n\n\t\t  *•.¸¸¸.•*¨¨*•.¸¸¸.•*•  ¸.•*¨¨*•.¸¸¸.•*•  •*\n"); 
	printf("\t\t   ¦ ¦ ¦ ¦ ¦B¦O¦M¦ ¦F¦I¦L¦M¦E¦ ¦A¦M¦¦  \n");
	printf("\t\t*•  *•.¸¸¸.•*¨¨*•.¸¸¸.•*• ¸.•*¨¨*•.¸¸¸.•*•  •«\n");
	Sleep(50);
	system("cls");
	printf("\n\n\t\t  *•.¸¸¸.•*¨¨*•.¸¸¸.•*•  ¸.•*¨¨*•.¸¸¸.•*•  •*\n"); 
	printf("\t\t   ¦ ¦ ¦ ¦B¦O¦M¦ ¦F¦I¦L¦M¦E¦ ¦A¦M¦I¦¦  \n");
	printf("\t\t*•  *•.¸¸¸.•*¨¨*•.¸¸¸.•*• ¸.•*¨¨*•.¸¸¸.•*•  •«\n");
	Sleep(50);
	system("cls");
	printf("\n\n\t\t  *•.¸¸¸.•*¨¨*•.¸¸¸.•*•  ¸.•*¨¨*•.¸¸¸.•*•  •*\n"); 
	printf("\t\t   ¦ ¦ ¦B¦O¦M¦ ¦F¦I¦L¦M¦E¦ ¦A¦M¦I¦G¦¦  \n");
	printf("\t\t*•  *•.¸¸¸.•*¨¨*•.¸¸¸.•*• ¸.•*¨¨*•.¸¸¸.•*•  •«\n");
	Sleep(50);
	system("cls");
	printf("\n\n\t\t  *•.¸¸¸.•*¨¨*•.¸¸¸.•*•  ¸.•*¨¨*•.¸¸¸.•*•  •*\n"); 
	printf("\t\t   ¦ ¦B¦O¦M¦ ¦F¦I¦L¦M¦E¦ ¦A¦M¦I¦G¦A¦¦  \n");
	printf("\t\t*•  *•.¸¸¸.•*¨¨*•.¸¸¸.•*• ¸.•*¨¨*•.¸¸¸.•*•  •«\n");
	Sleep(50);
	system("cls");
	printf("\n\n\t\t  *•.¸¸¸.•*¨¨*•.¸¸¸.•*•  ¸.•*¨¨*•.¸¸¸.•*•  •*\n"); 
	printf("\t\t   ¦B¦O¦M¦ ¦F¦I¦L¦M¦E¦ ¦A¦M¦I¦G¦A¦O¦¦   \n");
	printf("\t\t*•  *•.¸¸¸.•*¨¨*•.¸¸¸.•*• ¸.•*¨¨*•.¸¸¸.•*•  •«\n");
	Sleep(2000);
	system("cls");

	for(i=0;i<duracao;i++){
		printf("\n\n\t\t\tAssistindo... %d:%d / %2d.:%2d.", i/60, i%60, duracao/60, duracao%60);
		Sleep(30);
		system("cls");
	}
}
